# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_archeocad_Rect.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArcheoRect(object):
    def setupUi(self, ArcheoRect):
        ArcheoRect.setObjectName("ArcheoRect")
        ArcheoRect.resize(330, 669)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ArcheoRect.sizePolicy().hasHeightForWidth())
        ArcheoRect.setSizePolicy(sizePolicy)
        ArcheoRect.setMinimumSize(QtCore.QSize(330, 669))
        ArcheoRect.setMaximumSize(QtCore.QSize(330, 669))
        ArcheoRect.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(ArcheoRect)
        self.buttonBox.setGeometry(QtCore.QRect(140, 630, 161, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gBox_pointLayer = QtWidgets.QGroupBox(ArcheoRect)
        self.gBox_pointLayer.setGeometry(QtCore.QRect(10, 10, 311, 171))
        self.gBox_pointLayer.setObjectName("gBox_pointLayer")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.gBox_pointLayer)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 271, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkBoxSelected = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.chkBoxSelected.setObjectName("chkBoxSelected")
        self.horizontalLayout_2.addWidget(self.chkBoxSelected)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gBox_pointLayer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 90, 271, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TxtLabel_geoChoice = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TxtLabel_geoChoice.setObjectName("TxtLabel_geoChoice")
        self.verticalLayout.addWidget(self.TxtLabel_geoChoice)
        self.TxtLable_geoChoice2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TxtLable_geoChoice2.setObjectName("TxtLable_geoChoice2")
        self.verticalLayout.addWidget(self.TxtLable_geoChoice2)
        self.comboGeoChoice = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboGeoChoice.setObjectName("comboGeoChoice")
        self.verticalLayout.addWidget(self.comboGeoChoice)
        self.qgsComboPointLayer = QgsMapLayerComboBox(self.gBox_pointLayer)
        self.qgsComboPointLayer.setGeometry(QtCore.QRect(20, 30, 261, 21))
        self.qgsComboPointLayer.setObjectName("qgsComboPointLayer")
        self.gBox_multipleTr = QtWidgets.QGroupBox(ArcheoRect)
        self.gBox_multipleTr.setGeometry(QtCore.QRect(10, 190, 311, 131))
        self.gBox_multipleTr.setObjectName("gBox_multipleTr")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gBox_multipleTr)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 281, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkBoxFieldGroup = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chkBoxFieldGroup.setObjectName("chkBoxFieldGroup")
        self.horizontalLayout.addWidget(self.chkBoxFieldGroup)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gBox_multipleTr)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 251, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_regroup = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_regroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_regroup.setObjectName("label_regroup")
        self.verticalLayout_4.addWidget(self.label_regroup)
        self.comboGroup = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboGroup.setEnabled(False)
        self.comboGroup.setObjectName("comboGroup")
        self.verticalLayout_4.addWidget(self.comboGroup)
        self.gBox_Output = QtWidgets.QGroupBox(ArcheoRect)
        self.gBox_Output.setGeometry(QtCore.QRect(10, 480, 311, 121))
        self.gBox_Output.setObjectName("gBox_Output")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 261, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outFileLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.outFileLine.setObjectName("outFileLine")
        self.horizontalLayout_4.addWidget(self.outFileLine)
        self.ButtonBrowse = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.horizontalLayout_4.addWidget(self.ButtonBrowse)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 70, 261, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_enconding = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_enconding.setObjectName("label_enconding")
        self.horizontalLayout_5.addWidget(self.label_enconding)
        self.comboEncoding = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.comboEncoding.setObjectName("comboEncoding")
        self.horizontalLayout_5.addWidget(self.comboEncoding)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(ArcheoRect)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 600, 311, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gBox_multipleTr_2 = QtWidgets.QGroupBox(ArcheoRect)
        self.gBox_multipleTr_2.setGeometry(QtCore.QRect(10, 330, 311, 141))
        self.gBox_multipleTr_2.setObjectName("gBox_multipleTr_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.gBox_multipleTr_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 261, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Width = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_Width.setObjectName("label_Width")
        self.horizontalLayout_3.addWidget(self.label_Width)
        self.doubleSpinBoxWidth = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.doubleSpinBoxWidth.setDecimals(2)
        self.doubleSpinBoxWidth.setMaximum(999999999.99)
        self.doubleSpinBoxWidth.setObjectName("doubleSpinBoxWidth")
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxWidth)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.gBox_multipleTr_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 80, 261, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_orientation = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_orientation.setObjectName("label_orientation")
        self.verticalLayout_2.addWidget(self.label_orientation)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButtonLeft = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButtonLeft.setChecked(False)
        self.radioButtonLeft.setObjectName("radioButtonLeft")
        self.horizontalLayout_6.addWidget(self.radioButtonLeft)
        self.radioButtonRight = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButtonRight.setChecked(True)
        self.radioButtonRight.setObjectName("radioButtonRight")
        self.horizontalLayout_6.addWidget(self.radioButtonRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(ArcheoRect)
        self.buttonBox.accepted.connect(ArcheoRect.accept)
        self.buttonBox.rejected.connect(ArcheoRect.reject)
        self.chkBoxFieldGroup.toggled['bool'].connect(self.comboGroup.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ArcheoRect)

    def retranslateUi(self, ArcheoRect):
        _translate = QtCore.QCoreApplication.translate
        ArcheoRect.setWindowTitle(_translate("ArcheoRect", "ArcheoCAD Rectangle"))
        self.gBox_pointLayer.setTitle(_translate("ArcheoRect", "Input point layer"))
        self.chkBoxSelected.setText(_translate("ArcheoRect", "Create output features using only selected points"))
        self.TxtLabel_geoChoice.setText(_translate("ArcheoRect", "Input field containing the output geometry"))
        self.TxtLable_geoChoice2.setText(_translate("ArcheoRect", "(rectangle)"))
        self.gBox_multipleTr.setTitle(_translate("ArcheoRect", "Regrouping field"))
        self.chkBoxFieldGroup.setText(_translate("ArcheoRect", "Regrouping points based on a specific field"))
        self.label_regroup.setText(_translate("ArcheoRect", "Input field to be used to regroup points "))
        self.gBox_Output.setTitle(_translate("ArcheoRect", "Output shapefile"))
        self.ButtonBrowse.setText(_translate("ArcheoRect", "browse"))
        self.label_enconding.setText(_translate("ArcheoRect", "Character encoding"))
        self.gBox_multipleTr_2.setTitle(_translate("ArcheoRect", "Rectangle"))
        self.label_Width.setText(_translate("ArcheoRect", "Width (map\'s unit)"))
        self.label_orientation.setText(_translate("ArcheoRect", "Direction choice for creating the rectangle :"))
        self.radioButtonLeft.setText(_translate("ArcheoRect", "left"))
        self.radioButtonRight.setText(_translate("ArcheoRect", "right"))

from qgsmaplayercombobox import QgsMapLayerComboBox
