# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_archeocad.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ArcheoCAD(object):
    def setupUi(self, ArcheoCAD):
        ArcheoCAD.setObjectName("ArcheoCAD")
        ArcheoCAD.resize(330, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ArcheoCAD.sizePolicy().hasHeightForWidth())
        ArcheoCAD.setSizePolicy(sizePolicy)
        ArcheoCAD.setMinimumSize(QtCore.QSize(330, 702))
        ArcheoCAD.setMaximumSize(QtCore.QSize(330, 702))
        ArcheoCAD.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        ArcheoCAD.setSizeGripEnabled(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(ArcheoCAD)
        self.buttonBox.setGeometry(QtCore.QRect(130, 660, 181, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gBox_pointLayer = QtWidgets.QGroupBox(ArcheoCAD)
        self.gBox_pointLayer.setGeometry(QtCore.QRect(10, 10, 301, 181))
        self.gBox_pointLayer.setObjectName("gBox_pointLayer")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.gBox_pointLayer)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 271, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkBoxSelected = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.chkBoxSelected.setObjectName("chkBoxSelected")
        self.horizontalLayout_2.addWidget(self.chkBoxSelected)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gBox_pointLayer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 90, 261, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TxtLabel_geoChoice = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TxtLabel_geoChoice.setObjectName("TxtLabel_geoChoice")
        self.verticalLayout.addWidget(self.TxtLabel_geoChoice)
        self.TxtLable_geoChoice2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.TxtLable_geoChoice2.setObjectName("TxtLable_geoChoice2")
        self.verticalLayout.addWidget(self.TxtLable_geoChoice2)
        self.comboGeoChoice = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboGeoChoice.setObjectName("comboGeoChoice")
        self.verticalLayout.addWidget(self.comboGeoChoice)
        self.qgsComboPointLayer = QgsMapLayerComboBox(self.gBox_pointLayer)
        self.qgsComboPointLayer.setGeometry(QtCore.QRect(20, 30, 261, 21))
        self.qgsComboPointLayer.setObjectName("qgsComboPointLayer")
        self.gBox_multipleTr = QtWidgets.QGroupBox(ArcheoCAD)
        self.gBox_multipleTr.setGeometry(QtCore.QRect(10, 190, 311, 131))
        self.gBox_multipleTr.setObjectName("gBox_multipleTr")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.gBox_multipleTr)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 281, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkBoxFieldGroup = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.chkBoxFieldGroup.setObjectName("chkBoxFieldGroup")
        self.horizontalLayout.addWidget(self.chkBoxFieldGroup)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gBox_multipleTr)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 261, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_regroup = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_regroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_regroup.setObjectName("label_regroup")
        self.verticalLayout_4.addWidget(self.label_regroup)
        self.comboGroup = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboGroup.setEnabled(False)
        self.comboGroup.setObjectName("comboGroup")
        self.verticalLayout_4.addWidget(self.comboGroup)
        self.gBox_Output = QtWidgets.QGroupBox(ArcheoCAD)
        self.gBox_Output.setGeometry(QtCore.QRect(10, 470, 311, 161))
        self.gBox_Output.setObjectName("gBox_Output")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_VertexNb = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_VertexNb.setObjectName("label_VertexNb")
        self.horizontalLayout_3.addWidget(self.label_VertexNb)
        self.spinBoxNbVertices = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinBoxNbVertices.setWrapping(False)
        self.spinBoxNbVertices.setSpecialValueText("")
        self.spinBoxNbVertices.setPrefix("")
        self.spinBoxNbVertices.setMinimum(10)
        self.spinBoxNbVertices.setMaximum(999)
        self.spinBoxNbVertices.setProperty("value", 90)
        self.spinBoxNbVertices.setObjectName("spinBoxNbVertices")
        self.horizontalLayout_3.addWidget(self.spinBoxNbVertices)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 271, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outFileLine = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.outFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outFileLine.setObjectName("outFileLine")
        self.horizontalLayout_4.addWidget(self.outFileLine)
        self.ButtonBrowse = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName("ButtonBrowse")
        self.horizontalLayout_4.addWidget(self.ButtonBrowse)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 120, 271, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_enconding = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_enconding.setObjectName("label_enconding")
        self.horizontalLayout_5.addWidget(self.label_enconding)
        self.comboEncoding = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        self.comboEncoding.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.comboEncoding.setObjectName("comboEncoding")
        self.horizontalLayout_5.addWidget(self.comboEncoding)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(ArcheoCAD)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 630, 311, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gBox_Sort = QtWidgets.QGroupBox(ArcheoCAD)
        self.gBox_Sort.setGeometry(QtCore.QRect(10, 330, 311, 131))
        self.gBox_Sort.setObjectName("gBox_Sort")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.gBox_Sort)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 20, 236, 21))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chkBoxSort = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.chkBoxSort.setObjectName("chkBoxSort")
        self.horizontalLayout_6.addWidget(self.chkBoxSort)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.gBox_Sort)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 60, 251, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_sort = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_sort.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_sort.setObjectName("label_sort")
        self.verticalLayout_6.addWidget(self.label_sort)
        self.comboSort = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        self.comboSort.setEnabled(False)
        self.comboSort.setObjectName("comboSort")
        self.verticalLayout_6.addWidget(self.comboSort)

        self.retranslateUi(ArcheoCAD)
        self.buttonBox.accepted.connect(ArcheoCAD.accept)
        self.buttonBox.rejected.connect(ArcheoCAD.reject)
        self.chkBoxFieldGroup.toggled['bool'].connect(self.comboGroup.setEnabled)
        self.chkBoxSort.toggled['bool'].connect(self.comboSort.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ArcheoCAD)

    def retranslateUi(self, ArcheoCAD):
        _translate = QtCore.QCoreApplication.translate
        ArcheoCAD.setWindowTitle(_translate("ArcheoCAD", "ArcheoCAD - Poly-Circle-Ellipse"))
        self.gBox_pointLayer.setTitle(_translate("ArcheoCAD", "Input point layer"))
        self.chkBoxSelected.setText(_translate("ArcheoCAD", "Create output features using only selected points"))
        self.TxtLabel_geoChoice.setText(_translate("ArcheoCAD", "Input field containing the output geometry"))
        self.TxtLable_geoChoice2.setText(_translate("ArcheoCAD", "(polygon, circle, ellipse)"))
        self.gBox_multipleTr.setTitle(_translate("ArcheoCAD", "Regrouping field"))
        self.chkBoxFieldGroup.setText(_translate("ArcheoCAD", "Regrouping points based on a specific field"))
        self.label_regroup.setText(_translate("ArcheoCAD", "Input field to be used to regroup points "))
        self.gBox_Output.setTitle(_translate("ArcheoCAD", "Output shapefile"))
        self.label_VertexNb.setText(_translate("ArcheoCAD", "Number of vertices (used for circles and ellipses)"))
        self.ButtonBrowse.setText(_translate("ArcheoCAD", "browse"))
        self.label_enconding.setText(_translate("ArcheoCAD", "Character encoding"))
        self.gBox_Sort.setTitle(_translate("ArcheoCAD", "Sort polygon vertices"))
        self.chkBoxSort.setText(_translate("ArcheoCAD", "Sort vertices based on a specific field"))
        self.label_sort.setText(_translate("ArcheoCAD", "Input field to be used for the sort order"))

from qgsmaplayercombobox import QgsMapLayerComboBox
