# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_archeocad_Rect.ui'
#
# Created: Tue Dec 16 09:55:35 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ArcheoRect(object):
    def setupUi(self, ArcheoRect):
        ArcheoRect.setObjectName(_fromUtf8("ArcheoRect"))
        ArcheoRect.resize(330, 669)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ArcheoRect.sizePolicy().hasHeightForWidth())
        ArcheoRect.setSizePolicy(sizePolicy)
        ArcheoRect.setMinimumSize(QtCore.QSize(330, 669))
        ArcheoRect.setMaximumSize(QtCore.QSize(330, 669))
        ArcheoRect.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox = QtGui.QDialogButtonBox(ArcheoRect)
        self.buttonBox.setGeometry(QtCore.QRect(140, 630, 161, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gBox_pointLayer = QtGui.QGroupBox(ArcheoRect)
        self.gBox_pointLayer.setGeometry(QtCore.QRect(10, 10, 311, 171))
        self.gBox_pointLayer.setObjectName(_fromUtf8("gBox_pointLayer"))
        self.comboPointLayer = QtGui.QComboBox(self.gBox_pointLayer)
        self.comboPointLayer.setGeometry(QtCore.QRect(20, 20, 271, 22))
        self.comboPointLayer.setObjectName(_fromUtf8("comboPointLayer"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.gBox_pointLayer)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 271, 21))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkBoxSelected = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.chkBoxSelected.setObjectName(_fromUtf8("chkBoxSelected"))
        self.horizontalLayout_2.addWidget(self.chkBoxSelected)
        self.verticalLayoutWidget = QtGui.QWidget(self.gBox_pointLayer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 90, 251, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.TxtLabel_geoChoice = QtGui.QLabel(self.verticalLayoutWidget)
        self.TxtLabel_geoChoice.setObjectName(_fromUtf8("TxtLabel_geoChoice"))
        self.verticalLayout.addWidget(self.TxtLabel_geoChoice)
        self.TxtLable_geoChoice2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.TxtLable_geoChoice2.setObjectName(_fromUtf8("TxtLable_geoChoice2"))
        self.verticalLayout.addWidget(self.TxtLable_geoChoice2)
        self.comboGeoChoice = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboGeoChoice.setObjectName(_fromUtf8("comboGeoChoice"))
        self.verticalLayout.addWidget(self.comboGeoChoice)
        self.gBox_multipleTr = QtGui.QGroupBox(ArcheoRect)
        self.gBox_multipleTr.setGeometry(QtCore.QRect(10, 190, 311, 131))
        self.gBox_multipleTr.setObjectName(_fromUtf8("gBox_multipleTr"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.gBox_multipleTr)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 281, 21))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkBoxFieldGroup = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkBoxFieldGroup.setObjectName(_fromUtf8("chkBoxFieldGroup"))
        self.horizontalLayout.addWidget(self.chkBoxFieldGroup)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.gBox_multipleTr)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 251, 51))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_regroup = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_regroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_regroup.setObjectName(_fromUtf8("label_regroup"))
        self.verticalLayout_4.addWidget(self.label_regroup)
        self.comboGroup = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.comboGroup.setEnabled(False)
        self.comboGroup.setObjectName(_fromUtf8("comboGroup"))
        self.verticalLayout_4.addWidget(self.comboGroup)
        self.gBox_Output = QtGui.QGroupBox(ArcheoRect)
        self.gBox_Output.setGeometry(QtCore.QRect(10, 480, 311, 121))
        self.gBox_Output.setObjectName(_fromUtf8("gBox_Output"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 261, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outFileLine = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.outFileLine.setObjectName(_fromUtf8("outFileLine"))
        self.horizontalLayout_4.addWidget(self.outFileLine)
        self.ButtonBrowse = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.ButtonBrowse.setObjectName(_fromUtf8("ButtonBrowse"))
        self.horizontalLayout_4.addWidget(self.ButtonBrowse)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 70, 261, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_enconding = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_enconding.setObjectName(_fromUtf8("label_enconding"))
        self.horizontalLayout_5.addWidget(self.label_enconding)
        self.comboEncoding = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.comboEncoding.setObjectName(_fromUtf8("comboEncoding"))
        self.horizontalLayout_5.addWidget(self.comboEncoding)
        self.verticalLayoutWidget_3 = QtGui.QWidget(ArcheoRect)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 600, 311, 31))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gBox_multipleTr_2 = QtGui.QGroupBox(ArcheoRect)
        self.gBox_multipleTr_2.setGeometry(QtCore.QRect(10, 330, 311, 141))
        self.gBox_multipleTr_2.setObjectName(_fromUtf8("gBox_multipleTr_2"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.gBox_multipleTr_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 261, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_Width = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_Width.setObjectName(_fromUtf8("label_Width"))
        self.horizontalLayout_3.addWidget(self.label_Width)
        self.doubleSpinBoxWidth = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget_3)
        self.doubleSpinBoxWidth.setDecimals(2)
        self.doubleSpinBoxWidth.setMaximum(999999999.99)
        self.doubleSpinBoxWidth.setObjectName(_fromUtf8("doubleSpinBoxWidth"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBoxWidth)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.gBox_multipleTr_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 80, 261, 51))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_orientation = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_orientation.setObjectName(_fromUtf8("label_orientation"))
        self.verticalLayout_2.addWidget(self.label_orientation)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.radioButtonLeft = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButtonLeft.setChecked(False)
        self.radioButtonLeft.setObjectName(_fromUtf8("radioButtonLeft"))
        self.horizontalLayout_6.addWidget(self.radioButtonLeft)
        self.radioButtonRight = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButtonRight.setChecked(True)
        self.radioButtonRight.setObjectName(_fromUtf8("radioButtonRight"))
        self.horizontalLayout_6.addWidget(self.radioButtonRight)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(ArcheoRect)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ArcheoRect.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ArcheoRect.reject)
        QtCore.QObject.connect(self.chkBoxFieldGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboGroup.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ArcheoRect)

    def retranslateUi(self, ArcheoRect):
        ArcheoRect.setWindowTitle(_translate("ArcheoRect", "ArcheoCAD Rectangle", None))
        self.gBox_pointLayer.setTitle(_translate("ArcheoRect", "Input point layer", None))
        self.chkBoxSelected.setText(_translate("ArcheoRect", "Create output features using only selected points", None))
        self.TxtLabel_geoChoice.setText(_translate("ArcheoRect", "Input field containing the output geometry", None))
        self.TxtLable_geoChoice2.setText(_translate("ArcheoRect", "(rectangle)", None))
        self.gBox_multipleTr.setTitle(_translate("ArcheoRect", "Regrouping field", None))
        self.chkBoxFieldGroup.setText(_translate("ArcheoRect", "Regrouping points based on a specific field", None))
        self.label_regroup.setText(_translate("ArcheoRect", "Input field to be used to regroup points ", None))
        self.gBox_Output.setTitle(_translate("ArcheoRect", "Output shapefile", None))
        self.ButtonBrowse.setText(_translate("ArcheoRect", "browse", None))
        self.label_enconding.setText(_translate("ArcheoRect", "Character encoding", None))
        self.gBox_multipleTr_2.setTitle(_translate("ArcheoRect", "Rectangle", None))
        self.label_Width.setText(_translate("ArcheoRect", "Width (map\'s unit)", None))
        self.label_orientation.setText(_translate("ArcheoRect", "Direction choice for creating the rectangle :", None))
        self.radioButtonLeft.setText(_translate("ArcheoRect", "left", None))
        self.radioButtonRight.setText(_translate("ArcheoRect", "right", None))

