# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_archeocad.ui'
#
# Created: Wed Aug 13 17:16:46 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ArcheoCAD(object):
    def setupUi(self, ArcheoCAD):
        ArcheoCAD.setObjectName(_fromUtf8("ArcheoCAD"))
        ArcheoCAD.resize(330, 702)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ArcheoCAD.sizePolicy().hasHeightForWidth())
        ArcheoCAD.setSizePolicy(sizePolicy)
        ArcheoCAD.setMinimumSize(QtCore.QSize(330, 702))
        ArcheoCAD.setMaximumSize(QtCore.QSize(330, 702))
        ArcheoCAD.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        ArcheoCAD.setSizeGripEnabled(False)
        self.buttonBox = QtGui.QDialogButtonBox(ArcheoCAD)
        self.buttonBox.setGeometry(QtCore.QRect(130, 660, 181, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gBox_pointLayer = QtGui.QGroupBox(ArcheoCAD)
        self.gBox_pointLayer.setGeometry(QtCore.QRect(10, 10, 311, 171))
        self.gBox_pointLayer.setObjectName(_fromUtf8("gBox_pointLayer"))
        self.comboPointLayer = QtGui.QComboBox(self.gBox_pointLayer)
        self.comboPointLayer.setGeometry(QtCore.QRect(20, 20, 271, 22))
        self.comboPointLayer.setObjectName(_fromUtf8("comboPointLayer"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.gBox_pointLayer)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 271, 21))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chkBoxSelected = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.chkBoxSelected.setObjectName(_fromUtf8("chkBoxSelected"))
        self.horizontalLayout_2.addWidget(self.chkBoxSelected)
        self.verticalLayoutWidget = QtGui.QWidget(self.gBox_pointLayer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 261, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.TxtLabel_geoChoice = QtGui.QLabel(self.verticalLayoutWidget)
        self.TxtLabel_geoChoice.setObjectName(_fromUtf8("TxtLabel_geoChoice"))
        self.verticalLayout.addWidget(self.TxtLabel_geoChoice)
        self.TxtLable_geoChoice2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.TxtLable_geoChoice2.setObjectName(_fromUtf8("TxtLable_geoChoice2"))
        self.verticalLayout.addWidget(self.TxtLable_geoChoice2)
        self.comboGeoChoice = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboGeoChoice.setObjectName(_fromUtf8("comboGeoChoice"))
        self.verticalLayout.addWidget(self.comboGeoChoice)
        self.gBox_multipleTr = QtGui.QGroupBox(ArcheoCAD)
        self.gBox_multipleTr.setGeometry(QtCore.QRect(10, 190, 311, 131))
        self.gBox_multipleTr.setObjectName(_fromUtf8("gBox_multipleTr"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.gBox_multipleTr)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 281, 21))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkBoxFieldGroup = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.chkBoxFieldGroup.setObjectName(_fromUtf8("chkBoxFieldGroup"))
        self.horizontalLayout.addWidget(self.chkBoxFieldGroup)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.gBox_multipleTr)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 261, 51))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_regroup = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_regroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_regroup.setObjectName(_fromUtf8("label_regroup"))
        self.verticalLayout_4.addWidget(self.label_regroup)
        self.comboGroup = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.comboGroup.setEnabled(False)
        self.comboGroup.setObjectName(_fromUtf8("comboGroup"))
        self.verticalLayout_4.addWidget(self.comboGroup)
        self.gBox_Output = QtGui.QGroupBox(ArcheoCAD)
        self.gBox_Output.setGeometry(QtCore.QRect(10, 470, 311, 161))
        self.gBox_Output.setObjectName(_fromUtf8("gBox_Output"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_VertexNb = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_VertexNb.setObjectName(_fromUtf8("label_VertexNb"))
        self.horizontalLayout_3.addWidget(self.label_VertexNb)
        self.spinBoxNbVertices = QtGui.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinBoxNbVertices.setWrapping(False)
        self.spinBoxNbVertices.setSpecialValueText(_fromUtf8(""))
        self.spinBoxNbVertices.setPrefix(_fromUtf8(""))
        self.spinBoxNbVertices.setMinimum(10)
        self.spinBoxNbVertices.setMaximum(999)
        self.spinBoxNbVertices.setProperty("value", 90)
        self.spinBoxNbVertices.setObjectName(_fromUtf8("spinBoxNbVertices"))
        self.horizontalLayout_3.addWidget(self.spinBoxNbVertices)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 271, 31))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outFileLine = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.outFileLine.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.outFileLine.setObjectName(_fromUtf8("outFileLine"))
        self.horizontalLayout_4.addWidget(self.outFileLine)
        self.ButtonBrowse = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.ButtonBrowse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.ButtonBrowse.setObjectName(_fromUtf8("ButtonBrowse"))
        self.horizontalLayout_4.addWidget(self.ButtonBrowse)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.gBox_Output)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 120, 271, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_enconding = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_enconding.setObjectName(_fromUtf8("label_enconding"))
        self.horizontalLayout_5.addWidget(self.label_enconding)
        self.comboEncoding = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.comboEncoding.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.comboEncoding.setObjectName(_fromUtf8("comboEncoding"))
        self.horizontalLayout_5.addWidget(self.comboEncoding)
        self.verticalLayoutWidget_3 = QtGui.QWidget(ArcheoCAD)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 630, 311, 31))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gBox_Sort = QtGui.QGroupBox(ArcheoCAD)
        self.gBox_Sort.setGeometry(QtCore.QRect(10, 330, 311, 131))
        self.gBox_Sort.setObjectName(_fromUtf8("gBox_Sort"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.gBox_Sort)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 20, 236, 21))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkBoxSort = QtGui.QCheckBox(self.horizontalLayoutWidget_6)
        self.chkBoxSort.setObjectName(_fromUtf8("chkBoxSort"))
        self.horizontalLayout_6.addWidget(self.chkBoxSort)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.gBox_Sort)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 60, 251, 51))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_sort = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_sort.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_sort.setObjectName(_fromUtf8("label_sort"))
        self.verticalLayout_6.addWidget(self.label_sort)
        self.comboSort = QtGui.QComboBox(self.verticalLayoutWidget_4)
        self.comboSort.setEnabled(False)
        self.comboSort.setObjectName(_fromUtf8("comboSort"))
        self.verticalLayout_6.addWidget(self.comboSort)

        self.retranslateUi(ArcheoCAD)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ArcheoCAD.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ArcheoCAD.reject)
        QtCore.QObject.connect(self.chkBoxFieldGroup, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboGroup.setEnabled)
        QtCore.QObject.connect(self.chkBoxSort, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboSort.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ArcheoCAD)

    def retranslateUi(self, ArcheoCAD):
        ArcheoCAD.setWindowTitle(_translate("ArcheoCAD", "ArcheoCAD - Poly-Circle-Ellipse", None))
        self.gBox_pointLayer.setTitle(_translate("ArcheoCAD", "Input point layer", None))
        self.chkBoxSelected.setText(_translate("ArcheoCAD", "Create output features using only selected points", None))
        self.TxtLabel_geoChoice.setText(_translate("ArcheoCAD", "Input field containing the output geometry", None))
        self.TxtLable_geoChoice2.setText(_translate("ArcheoCAD", "(polygon, circle, ellipse)", None))
        self.gBox_multipleTr.setTitle(_translate("ArcheoCAD", "Regrouping field", None))
        self.chkBoxFieldGroup.setText(_translate("ArcheoCAD", "Regrouping points based on a specific field", None))
        self.label_regroup.setText(_translate("ArcheoCAD", "Input field to be used to regroup points ", None))
        self.gBox_Output.setTitle(_translate("ArcheoCAD", "Output shapefile", None))
        self.label_VertexNb.setText(_translate("ArcheoCAD", "Number of vertices (used for circles and ellipses)", None))
        self.ButtonBrowse.setText(_translate("ArcheoCAD", "browse", None))
        self.label_enconding.setText(_translate("ArcheoCAD", "Character encoding", None))
        self.gBox_Sort.setTitle(_translate("ArcheoCAD", "Sort polygon vertices", None))
        self.chkBoxSort.setText(_translate("ArcheoCAD", "Sort vertices based on a specific field", None))
        self.label_sort.setText(_translate("ArcheoCAD", "Input field to be used for the sort order", None))

